from src.items.params_schemas import *
from typing import Dict, Type, Union
from pydantic import BaseModel
from itertools import chain

MAX_LIMIT_SIMILAR: int = 25
MAX_LIMIT_ITEMS: int = 40

CATEGORIZED_PARAMS_SCHEMAS: Dict[str, Dict[str, Type[BaseModel]]] = {
    "electronics": {
        "smartphone": SmartphoneParams,
        "laptop": LaptopParams,
        "tablet": TabletParams,
        "monitor": MonitorParams,
        "television": TVParams,
        "pc": PCParams,
        "gaming-console": GamingConsoleParams,
        "vr-headset": VRHeadsetParams,
        "camera": CameraParams,
        "router": RouterParams,
        "smartwatch": SmartwatchParams,
        "fitness-tracker": FitnessTrackerParams,
        "drone": DroneParams,
        "vr-controller": VRControllerParams,
        "ar-glasses": ARGlassesParams,
        "3d-printer": Printer3DParams,
    },
    "home-appliances": {
        "refrigerator": RefrigeratorParams,
        "freezer": FreezerParams,
        "washing-machine": WashingMachineParams,
        "dishwasher": DishwasherParams,
        "microwave": MicrowaveParams,
        "oven": OvenParams,
        "coffee-maker": CoffeeMakerParams,
        "blender": BlenderParams,
        "toaster": ToasterParams,
        "kettle": KettleParams,
        "juicer": JuicerParams,
        "slow-cooker": SlowCookerParams,
        "rice-cooker": RiceCookerParams,
        "bread-maker": BreadMakerParams,
        "food-processor": FoodProcessorParams,
        "air-fryer": AirFryerParams,
        "deep-fryer": DeepFryerParams,
        "grill": GrillParams,
        "barbecue": BarbecueParams,
        "smoker": SmokerParams,
        "air-purifier": AirPurifierParams,
        "humidifier": HumidifierParams,
        "dehumidifier": DehumidifierParams,
        "heater": HeaterParams,
        "fan": FanParams,
        "vacuum-cleaner": VacuumCleanerParams,
        "robot-vacuum": RobotVacuumParams,
    },
    "сomputing-office": {
        "printer": PrinterParams,
        "scanner": ScannerParams,
        "photocopier": PhotocopierParams,
        "fax-machine": FaxMachineParams,
        "plotter": PlotterParams,
        "power-bank": PowerBankParams,
        "charger": ChargerParams,
        "ups": UPSParams,
    },
    "audio-video": {
        "headphones": HeadphonesParams,
        "speaker": SpeakerParams,
        "subwoofer": SubwooferParams,
        "microphone": MicrophoneParams,
        "audio-mixer": AudioMixerParams,
        "amplifier": AmplifierParams,
        "receiver": ReceiverParams,
        "projector": ProjectorParams,
        "projector-screen": ProjectorScreenParams,
        "turntable": TurntableParams,
        "dj-controller": DJControllerParams,
    },
    "furniture": {
        "table": TableParams,
        "desk": DeskParams,
        "chair": ChairParams,
        "sofa": SofaParams,
        "bed": BedParams,
        "wardrobe": WardrobeParams,
        "dresser": DresserParams,
        "nightstand": NightstandParams,
        "shelf": ShelfParams,
        "mirror": MirrorParams,
        "rug": RugParams,
        "cabinet": CabinetParams,
        "bookshelf": ShelfParams,
    },
    "lighting": {
        "desk-lamp": DeskLampParams,
        "floor-lamp": FloorLampParams,
        "chandelier": ChandelierParams,
        "spotlight": SpotlightParams,
    },
    "tools-electronics": {
        "3d-printer": Printer3DParams,
        "cnc-machine": CNCMachineParams,
        "pcb-printer": PCBPrinterParams,
        "soldering-station": SolderingStationParams,
        "multimeter": MultimeterParams,
        "oscilloscope": OscilloscopeParams,
        "signal-generator": SignalGeneratorParams,
        "power-supply": PowerSupplyParams,
        "battery-tester": BatteryTesterParams,
        "voltage-stabilizer": VoltageStabilizerParams,
        "inverter": InverterParams,
        "transformer": TransformerParams,
        "portable-generator": PortableGeneratorParams,
        "solar-panel": SolarPanelParams,
    },
    "sports-outdoors": {
        "bicycle": BicycleParams,
        "electric-scooter": ElectricScooterParams,
        "skateboard": SkateboardParams,
        "roller-skates": RollerSkatesParams,
        "tent": TentParams,
        "sleeping-bag": SleepingBagParams,
        "camping-stove": CampingStoveParams,
    },
    "apparel-footwear": {
        "clothing": ClothingParams,
        "footwear": FootwearParams,
    },
    "toys-games": {
        "board-game": BoardGameParams,
        "puzzle": PuzzleParams,
    },
    "baby-kids": {
        "stroller": BabyStrollerParams,
        "car-seat": CarSeatParams,
        "high-chair": HighChairParams,
        "crib": CribParams,
        "mattress": MattressParams,
        "pillow": PillowParams,
        "blanket": BlanketParams,
    },
    "books-stationery": {
        "book": BookParams,
        "stationery": StationeryParams,
    },
    "food": {
        "food": FoodParams,
    }
}
